services:
  terraform:
    image: terraform-azure:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: terraform-azure
    environment:
      ARM_CLIENT_ID: ${ARM_CLIENT_ID}
      ARM_CLIENT_SECRET: ${ARM_CLIENT_SECRET}
      ARM_SUBSCRIPTION_ID: ${ARM_SUBSCRIPTION_ID}
      ARM_TENANT_ID: ${ARM_TENANT_ID}
    volumes:
      - ./terraform:/app/terraform
